# Generated by Django 4.2.23 on 2025-07-16 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tarea',
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['completo']},
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='complete',
            new_name='completo',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='created',
        ),
        migrations.AddField(
            model_name='tarea',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
