# Generated by Django 4.2.23 on 2025-07-16 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_task_tarea_alter_tarea_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Task',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completo',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='usuario',
            new_name='user',
        ),
    ]
